export const changelog = [
  {
    version: "1.25.0",
    date: "2026-10-04",
    title: "Flora, fracture and free-falling elastics",
    changes: [
      "Crystal replaces Prism, sources move to Materials, and Flora gains moisture-fed Fungus and host-dependent Virus.",
      "Sponge now stretches and absorbs as an elastic, while deformed spring meshes keep falling without supporting themselves.",
      "More brittle solids shed weak pieces in the air and crumble on impact, with air and impact stress capped at 64 and 128 samples per tick.",
      "Saved oxidation levels replace Patina, change Copper’s color and conduction, and migrate old Patina and Wire worlds to Copper.",
    ],
  },
  {
    version: "1.24.0",
    date: "2026-10-04",
    title: "Light, spectra and sound",
    changes: [
      "Shared absorption, reflectiveness, refraction and dispersion now drive shadows, recast lighting, Lasers and rainbow Photon packets through Prism.",
      "Lamps no longer shadow themselves, and illumination reaches a shallow layer inside opaque surfaces.",
      "Cached-light fire benchmarks fell from 26.3 to 10.4 ms per frame, while paired moving-plume rendering fell from 20.9 to 18.1 ms.",
      "Flames rise diagonally without crossing closed corners, and combustion avoids per-cell callback allocations.",
      "Material sound transmission, absorption and dispersion now shape Echolocation, muffling and finite echoes.",
      "Automatic phone-speaker output improves audibility, portrait distance falloff matches landscape, and group-name inputs avoid automatic mobile zoom.",
    ],
  },
  {
    version: "1.23.0",
    date: "2026-10-04",
    title: "Cloud weather and sticky elastics",
    changes: [
      "Renamed Kerosene to Fuel and Steel Powder to Metal Dust, and replaced Wood Chips with lighter, absorbent, faster-burning Sawdust.",
      "Glue stretches, sticks to static surfaces, releases under heat or tension, and softens into liquid when heated.",
      "Cloud density, temperature, mixed ice and droplets, and updrafts now drive rain, snow and lightning instead of a Storm emitter.",
    ],
  },
  {
    version: "1.22.1",
    date: "2026-10-04",
    title: "Group controls",
    changes: [
      "The plus now follows the last group, with a removal mode for deleting custom groups or hiding and restoring built-in groups.",
    ],
  },
  {
    version: "1.22.0",
    date: "2026-10-04",
    title: "Components and moving air",
    changes: [
      "Material groups now form a right-hand rail that expands from icons to names on desktop and mobile.",
      "Water carries Salt or Soap, and Dirt and Clay retain water in pores, replacing separate mixture materials while preserving old saves.",
      "Ingredients alter density, viscosity, freezing, foaming and corrosion, and survive absorption, evaporation and editing.",
      "Moving grains, liquids, solids and elastics push the shared air field with bounded local momentum transfer.",
      "Gas density is positive and separate from buoyancy, and Mirror now has glass density.",
    ],
  },
  {
    version: "1.21.0",
    date: "2026-10-04",
    title: "Material-driven sound",
    changes: [
      "Impacts use mass, brittleness, friction, conductivity and elastic softness, with porous surfaces damping sound.",
      "Liquid flow responds to viscosity and density, while reaction sounds follow their pressure, heat and gas production.",
      "Shared procedural voices retain spatial muffling and echoes with a bounded 96-buffer cache.",
    ],
  },
  {
    version: "1.20.0",
    date: "2026-10-03",
    title: "Natural sound and room acoustics",
    changes: [
      "Added swooshes and sloshes, with distinct procedural splashes, bubbling, fizzing, impacts and fire crackles.",
      "Placed Players hear wall-muffled sound and short surface echoes using Echolocation’s shared barriers and absorption.",
      "A sealed-room sound burst now settles in 154 ticks (2.6 seconds), versus more than 600 ticks in the previous benchmark.",
      "One bounded listener field serves all voices, averaging 0.35 ms for eight queries in a 320×200 development benchmark.",
      "Audio settings now include Wall muffling and Room echoes toggles.",
    ],
  },
  {
    version: "1.19.1",
    date: "2026-10-03",
    title: "Faster fire lighting and lightning flashes",
    changes: [
      "Fire lighting refreshes are 45–51% faster in desktop browser stress tests, with dense flames improving from 47.96 to 25.67 ms and repeated ray traces reduced by 95–97%.",
      "Light reaches farther with smooth falloff, directional shadows and faint smoke scattering.",
      "Lightning illuminates the whole scene with a fading flash instead of a separate shadow pass for each bolt segment.",
      "Changelog entries now use short, one-sentence bullets and measured optimization results.",
    ],
  },
  {
    version: "1.19.0",
    date: "2026-10-03",
    title: "Pixel-exact brushes and contained-fluid mass",
    changes: [
      "Brush Size now measures the exact diameter in canvas pixels, from 1 to 61, with matching outlines and tool footprints.",
      "Absorbed liquids add weight and rotational inertia to solids and elastics without rebuilding their shapes.",
      "Inspect reports loaded mass, and existing brush preferences and saves remain compatible.",
    ],
  },
  {
    version: "1.18.0",
    date: "2026-10-03",
    title: "Composable materials and faster solid rendering",
    changes: [
      "Materials use reusable traits and a validated registry while preserving all 130 definitions and existing save IDs.",
      "Cached solid textures reduced a 16,000-cell drawing pass from 18.45 to 1.78 ms in development benchmarks.",
      "Compiled heat-transfer tables retained comparable dense-fluid performance at 14.8 versus 14.7 ms per tick.",
      "The optional debug panel shows separate simulation and rendering timings.",
      "Round solids roll more reliably down shallow pixel slopes.",
    ],
  },
  {
    version: "1.17.1",
    date: "2026-10-03",
    title: "Fit and stretch canvas views",
    changes: [
      "A button beside Fullscreen switches between Fit and Stretch, with the choice saved in Rendering settings.",
      "Drawing, inspection, selection and camera gestures follow both display modes and phone rotation.",
    ],
  },
  {
    version: "1.17.0",
    date: "2026-10-03",
    title: "Shared pores, pressure and cleaner controls",
    changes: [
      "Removed the selected-material footer and renamed Rocket to Missile and Wind to Blow.",
      "Wind and pressure share one system that pushes bodies, flows around obstacles and fractures overloaded brittle surfaces.",
      "Airflow view shows direction, streamlines, compression and suction.",
      "Settings and toolbar groups have more space, clearer alignment and larger touch targets.",
      "All porous materials share Porosity, Permeability and Retention for liquid storage and flow.",
      "Absorbed liquids survive movement, editing and saves, while heat, freezing and pressure affect their release.",
      "Liquid transport uses staggered local checks and prevents fluid from crossing an entire bed in one tick.",
    ],
  },
  {
    version: "1.16.0",
    date: "2026-10-03",
    title: "Linked portals",
    changes: [
      "Added Portal, a Static material whose separately drawn shapes can be linked by dragging between them.",
      "Linked portals transport particles and fitting bodies while preserving their properties and redirecting motion.",
      "Blocked exits retain incoming objects, cooldowns prevent teleport loops, and links survive editing and saves.",
    ],
  },
  {
    version: "1.15.2",
    date: "2026-10-03",
    title: "Keyboard bindings and missile names",
    changes: [
      "Renamed Laser-Guided Missile to Guided Missile and Heat-Seeking Missile to Seeking Missile.",
      "Keyboard settings support adding, editing and deleting bindings while rejecting conflicting keys.",
      "Default bindings are limited to Pause, Undo, Redo, Cut, Copy, Paste and Save, with Space assigned only to Pause.",
      "Player movement and jumping remain available as optional keyboard bindings.",
    ],
  },
  {
    version: "1.15.1",
    date: "2026-10-03",
    title: "Canvas dimensions and unified tool controls",
    changes: [
      "Canvas settings always show both dimensions, with the longer dimension calculated and disabled on mobile.",
      "Removed the main-screen resolution label and moved View beside Canvas properties and Fullscreen.",
      "All brush settings and tool-specific properties now live in the Tool group.",
    ],
  },
  {
    version: "1.15.0",
    date: "2026-10-03",
    title: "Porous flow and steadier mobile controls",
    changes: [
      "Changing tools preserves the mobile drawer state, and rotation synchronizes gravity with the view.",
      "Porosity and permeability let liquids rise through grains, find nearby outlets or remain trapped beneath dense beds.",
      "Inspect shows density, porosity, permeability and brittleness.",
      "Brittle solids fracture more easily under impacts while Wall remains indestructible.",
    ],
  },
  {
    version: "1.14.5",
    date: "2026-10-03",
    title: "Home-screen icon and logo menu",
    changes: [
      "Home-screen installs and the browser favicon use the supplied three-grain icon.",
      "Clicking the logo opens About, replacing the question-mark button.",
      "The Changelog button is right-aligned in About.",
    ],
  },
  {
    version: "1.14.4",
    date: "2026-10-03",
    title: "Simpler tools and clearer brush controls",
    changes: [
      "Removed zoom buttons, Fan and Squeeze tools while retaining gesture zoom and powered fans.",
      "Renamed Paint to Color and the sampling tool to Pick, with an eyedropper icon.",
      "Brush size sits in the tool group, playback speed has a border, and category tabs show monochrome icons.",
      "Simplified Import, Export and keyboard settings, and added space around the world name.",
      "Added switches for wind, pressure and temperature simulation.",
      "GitHub Pages became the sole publishing destination.",
    ],
  },
  {
    version: "1.14.3",
    date: "2026-10-03",
    title: "Grouped controls and controller support",
    changes: [
      "Desktop and mobile controls use clearly bordered groups for drawing, playback, editing and tool categories.",
      "The material dropdown toggles the desktop sidebar, and About shows the registered interaction count.",
      "Added controller support for sandbox tools, camera movement, menus and the Player.",
      "Controller settings include deadzone, cursor speed and button bindings.",
    ],
  },
  {
    version: "1.14.2",
    date: "2026-10-03",
    title: "Smooth lighting and directional shadows",
    changes: [
      "Lights follow individual particle silhouettes to cast directional shadows through narrow openings.",
      "Smooth lighting preserves dark wall faces while supporting colored light, glass, water and reflections.",
      "Angular shadow maps and unchanged-scene caching bound lighting work while refreshing edits.",
      "Focused development checks and deployment filtering avoid unnecessary testing and publication.",
    ],
  },
  {
    version: "1.14.1",
    date: "2026-10-03",
    title: "Bounded solid collisions",
    changes: [
      "Touching solids synchronize body motion once per tick instead of rescanning neighbors for every contact.",
      "Collision work is capped at 16 contact manifolds per move and 64 placement nodes without deleting blocked particles.",
      "Fracture damage is combined once per particle, and diagnostics show body counts, contacts and collision checks.",
    ],
  },
  {
    version: "1.14.0",
    date: "2026-10-03",
    title: "Entities and canvas modes",
    changes: [
      "Moved creatures, missiles, vehicles and devices into a separate Entities catalog.",
      "Added laser-guided missiles, unguided rockets and a Guide tool for cursor or touch targeting.",
      "Added Planet, Wandering Gravity, Whirlpool, Zero Gravity and Day And Night canvas modes.",
      "Broken pieces of three pixels or fewer can become material-specific debris while retaining heat, color and momentum.",
    ],
  },
  {
    version: "1.13.0",
    date: "2026-10-03",
    title: "Wind and vented pressure",
    changes: [
      "Pressure drives localized wind through openings, carrying heat, smoke and flames around barriers.",
      "Added a Wind brush, ambient wind settings, Airflow view and a Vented fire chamber example.",
      "Wind respects gravity rotation, material density, borders and saved world state.",
      "A complete 400×300 air field averaged 0.53 ms per tick in development benchmarks.",
    ],
  },
  {
    version: "1.12.0",
    date: "2026-10-02",
    title: "Custom groups and real devices",
    changes: [
      "Simplified material categories and added editable custom groups saved in the browser.",
      "Added wires, batteries, directional logic gates, a signal lamp and an electric fan.",
      "Added Drone and Rover with configurable motors, movement, damage and persistent state.",
      "Added Logic workbench and Device yard example worlds.",
    ],
  },
  {
    version: "1.11.1",
    date: "2026-10-02",
    title: "60 FPS and tick limits",
    changes: [
      "Rendering and physics are capped at 60 per second, with missed ticks dropped instead of catch-up bursts.",
      "Simulation speed offers 0.25×, 0.5× and 1×, with tick-rate diagnostics.",
    ],
  },
  {
    version: "1.11.0",
    date: "2026-10-02",
    title: "Flocks and fish schools",
    changes: [
      "Birds and aquatic creatures use Boids to flock or school while avoiding hazards and prioritizing survival.",
      "Wildlife settings control group distance and size, with a Flocks and schools example world.",
      "Flock steering shares a deterministic snapshot and reusable buffers across the capped creature population.",
    ],
  },
  {
    version: "1.10.2",
    date: "2026-10-02",
    title: "Walking over slopes",
    changes: [
      "Players and stickmen step onto one- and two-pixel ledges when their legs and overhead clearance allow it.",
      "Feet stay planted on uneven slopes after movement stops while preserving jumps and external pushes.",
    ],
  },
  {
    version: "1.10.1",
    date: "2026-10-02",
    title: "Planted feet after walking",
    changes: [
      "Fixed grounded character drift after movement stops and prevented AI followers from pushing stationary players.",
    ],
  },
  {
    version: "1.10.0",
    date: "2026-10-02",
    title: "Local light and dark canvases",
    changes: [
      "Lamps, fire, hot surfaces and electrical effects cast colored light and shadows across the scene.",
      "Added adjustable faint surface reflections that respect sealed walls.",
      "Canvas settings include Ambient light, with unlit areas black at 0%.",
      "Lighting covers particles, bodies, creatures, painted backgrounds and previews while diagnostic views remain readable.",
    ],
  },
  {
    version: "1.9.0",
    date: "2026-10-02",
    title: "Predators and heat seekers",
    changes: [
      "Added Wolves and Sharks, predator hunting, prey escape and configurable sensing distances.",
      "Added heat-seeking missiles with configurable targeting, speed, range and explosions.",
      "Added Predator reserve and Missile range example worlds.",
      "Player settings include joystick side, size, inset and vertical position.",
    ],
  },
  {
    version: "1.8.0",
    date: "2026-10-02",
    title: "Creatures and echolocation",
    changes: [
      "Character speed and jump height scale to body size, with walking around one body height per second.",
      "Added Cats, Rabbits, Fish, Birds and a Wildlife pond world, with jointed, burnable and breakable bodies.",
      "Removed Light and Sound materials while preserving Laser, Mirror and Solar Cell.",
      "Added stereo effects for impacts, chemistry, phase changes, fire, explosions and creatures, with the listener following the player.",
      "Added Echolocation to visualize sound propagation, reflection and absorption even when audio is muted.",
    ],
  },
  {
    version: "1.7.1",
    date: "2026-10-02",
    title: "Joystick jumping",
    changes: [
      "Replaced the mobile Jump button with joystick-up jumping and joystick-down crouching.",
    ],
  },
  {
    version: "1.7.0",
    date: "2026-10-02",
    title: "Stickmen and player controls",
    changes: [
      "Added Stickman and Player with jointed bodies, collisions, burning, damage and breakable limbs.",
      "AI stickmen use bounded A* navigation with jumps, drops and hazard avoidance.",
      "Added desktop movement controls and a mobile joystick with jumping.",
      "Added Stickman playground, persistent character saves and live body inspection.",
    ],
  },
  {
    version: "1.6.6",
    date: "2026-10-02",
    title: "Shape solids before they fall",
    changes: [
      "Drawing moving solids pauses physics until the shape is finished.",
      "Brush settings offer Resume on release or Stay paused while preserving existing pauses.",
      "Stationary strokes skip repeated brush work without delaying live brush changes.",
    ],
  },
  {
    version: "1.6.5",
    date: "2026-10-02",
    title: "Pixel material icons",
    changes: [
      "Added distinct pixel icons for every material category.",
      "Material cards share centered icons and labels across desktop and mobile.",
    ],
  },
  {
    version: "1.6.4",
    date: "2026-10-02",
    title: "Centered material cards",
    changes: [
      "Centered material icons and labels in desktop, phone and tablet grid cards.",
    ],
  },
  {
    version: "1.6.3",
    date: "2026-10-02",
    title: "Material cleanup",
    changes: [
      "Removed Fit canvas buttons and ten retired materials from the palette and reactions.",
      "Renamed Carbon Dioxide to CO2 and Glass Dust to Glass Shards, with title-case material names.",
      "Older saves migrate to remaining materials, including shared Acid and Baking Soda reactions.",
    ],
  },
  {
    version: "1.6.2",
    date: "2026-10-02",
    title: "Rolling solids and faster physics",
    changes: [
      "Solids roll, slide and spin using friction, bounce and angular momentum without catching on their own cells.",
      "Inactive chemistry and repeated force calculations are skipped while preserving material interactions.",
      "Development benchmarks improved 54,400-liquid simulation from 16.71 to 9.77 ms per tick and 43,305-powder simulation from 12.89 to 6.62 ms.",
      "Dense tumbling solids became more expensive at 12.10 to 25.54 ms per tick as rotation and contact physics improved.",
      "Electricity and heat follow structural links through rotating solids, with an updated Live wire example.",
    ],
  },
  {
    version: "1.6.1",
    date: "2026-10-02",
    title: "Two-finger navigation",
    changes: [
      "Two fingers pan and pinch around their midpoint, including rotated mobile views.",
      "Gesture startup avoids accidental dots, and both fingers must lift before drawing resumes.",
      "Navigation preserves particle state and history while preventing browser scrolling and zooming.",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-10-02",
    title: "Bucket fill and moving solid bodies",
    changes: [
      "Added undoable bucket fill for materials, foreground color and background color.",
      "Added Static Wall as a fixed, indestructible support material.",
      "Solids fall as connected bodies with mass, rotation, buoyancy, pressure response and impact damage.",
      "Rigid shapes retain their geometry through grabbing, cutting, copying, resizing and saves.",
      "Cached elastic connectivity reduced a 5,600-node benchmark from 8.77 to 8.26 ms per tick.",
      "Merged the acids into one Acid material with compatible saves and shared reactions.",
      "Fixed wall-corner collisions, balanced supports and flame contact during ignition.",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-10-02",
    title: "Fitted canvases, rotating gravity, and foaming chemistry",
    changes: [
      "Removed placement temperature and moved Replace beside the material picker.",
      "Baking Soda and acids produce CO2, expanding foam and localized pressure.",
      "Added ambient and localized air temperature with barrier-aware heat and pressure transport.",
      "Replaced generic substances with named materials and expanded corrosion, gas production and phase changes.",
      "Fixed elastics catching on their own connected particles.",
      "Canvases fill the available screen, with mobile resolution based on the shorter dimension.",
      "Phone rotation preserves world coordinates while gravity follows screen-down.",
      "Mobile controls stay at the bottom and share the rotated drawing and camera transform.",
      "Resolution changes retain positioned cropping, Undo/Redo and compatible saves.",
    ],
  },
  {
    version: "1.4.1",
    date: "2026-10-01",
    title: "Paint, elastic motion, and canvas handles",
    changes: [
      "Added foreground and background painting without placing particles or changing physics.",
      "Added a color wheel, RGB and hex inputs, color sliders, opacity and a palette.",
      "Paint persists through editing, copying and saves.",
      "Elastics fall faster, maintain tension and continue moving after cuts.",
      "Elastic skins render separately and thin under tension across views and previews.",
      "Erasing cuts stretched links and lets tensioned strands recoil.",
      "Moved Fertilizer to Powders and added undoable desktop canvas resize handles.",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-10-01",
    title: "Elastics and bubbles",
    changes: [
      "Added Rope, Rubber and Jelly with persistent spring connections, anchoring and elastic motion.",
      "Added Soap, Soapy Water and Bubbles that rise and pop under heat, pressure or age.",
      "Each substance has one palette entry while alternate phases remain simulated.",
      "Reorganized material categories by behavior and made mobile grid tiles equally sized.",
      "Mobile controls group playback, editing, brushes and properties logically.",
      "Elastic links persist through saves, selections, copying and resizing.",
    ],
  },
  {
    version: "1.3.1",
    date: "2026-10-01",
    title: "Phone rotation and fullscreen",
    changes: [
      "Reduced the mobile dock to one row with a grip and a visible fullscreen exit.",
      "Landscape refits the canvas and chooses side or bottom controls to preserve drawing space.",
      "Swipe gestures expand panels while rotation preserves particles and restores portrait layout.",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-10-01",
    title: "Drawing and canvas space",
    changes: [
      "Shift-drag previews a line and Control-drag previews a circle or rectangle before drawing.",
      "Scrolling changes brush size, Control-scroll zooms and middle-drag pans.",
      "A compact mobile dock expands by tap or swipe to reveal editing controls.",
      "Canvas focus works in iPhone Safari while retaining the animated material browser.",
    ],
  },
  {
    version: "1.2.2",
    date: "2026-10-01",
    title: "Mobile toolbar",
    changes: [
      "Fixed the mobile View control overlapping Trash and aligned the toolbar touch targets.",
    ],
  },
  {
    version: "1.2.1",
    date: "2026-10-01",
    title: "Tool names",
    changes: [
      "Renamed Paint to Draw, Magnifier to Inspect and Eyedropper to Copy.",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-10-01",
    title: "Energy and imagination",
    changes: [
      "Added matching line icons and keyboard navigation to the tool dropdown.",
      "Added light, lasers, sound, neutrons, mirrors, solar cells, uranium and glass dust with corresponding interactions.",
      "Added fictional materials including dragonfire, frostfire, antimatter, black holes, repulsors and fairy dust.",
      "Ray directions persist through copying, resizing, history and saves.",
      "Lightning brush size controls strike frequency while taps strike immediately.",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-10-01",
    title: "Canvas creation and resizing",
    changes: [
      "Replaced Experiments with named canvases supporting custom dimensions, borders and background colors.",
      "Canvas resizing includes a draggable preview for cropping or adding space.",
      "Solid, looping and void borders govern particle escape, reactions, heat and pressure.",
      "Canvas properties persist through saves and history, and menu closure no longer overrides pause shortcuts.",
    ],
  },
  {
    version: "1.0.1",
    date: "2026-10-01",
    title: "About Sandlab",
    changes: [
      "The About menu shows app information and the changelog instead of redundant controls.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Inspection and keyboard controls",
    changes: [
      "Added live material inspection and an eyedropper for sampling the world.",
      "Keyboard shortcuts can be edited, cleared or reset in Settings.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Edit history and reaction timing",
    changes: [
      "Added Redo, selection editing, desktop shortcuts and the changelog.",
      "Gunpowder burns progressively, liquid fuel burns at exposed surfaces and TNT reacts after a delay.",
      "Burning fuel emits embers and conductors spark across small gaps.",
      "Cold water quenches flames and Brine retains salt during boiling and freezing.",
      "Removed Terrarium and made empty worlds the default.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Public access and security",
    changes: [
      "Sandlab became playable without a ChatGPT sign-in.",
      "Blocked remote scripts and connections, removed remote fonts and hardened save imports.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Materials and experiments",
    changes: [
      "Expanded the palette to 71 materials, including Copper, Sodium, Clay, Fertilizer and Liquid Nitrogen.",
      "Added oxidation, neutralization, nutrient transport, ceramic firing and two example worlds.",
    ],
  },
  {
    date: "Earlier updates",
    title: "Sandbox controls",
    changes: [
      "Added lightning, plants, bloom, absorption, temperature tools and force tools.",
      "Added brush and rectangle selections with copying, pasting, dragging and deselection.",
      "Added grouped settings and a full-height mobile material palette.",
    ],
  },
];
