export const changelog = [
  {
    version: "1.10.1",
    date: "2026-10-02",
    title: "Planted feet after walking",
    changes: [
      "Grounded characters now resolve static foot grip after pose and joint corrections, preventing those corrections from reintroducing a sideways drift after walking stops. Keyboard and joystick release both benefit. AI followers stop nearby instead of walking into a stationary player and pushing them. Jump momentum, strong external pushes, moving supports, detached limbs and ragdolls retain their physics.",
    ],
  },
  {
    version: "1.10.0",
    date: "2026-10-02",
    title: "Local light and dark canvases",
    changes: [
      "Added Lamp to Devices. Lamps, fire, sparks, lightning, electrical charge, burning material, hot surfaces and missile exhaust illuminate nearby matter with radial falloff. Opaque surfaces cast shadows; glass and water transmit light.",
      "Added a faint reflected-light pass that picks up surface color and travels around nearby corners without leaking through sealed walls. Settings → Rendering → Reflected light controls the bounce amount; Bloom remains a separate glow effect.",
      "New canvas and Canvas properties now include Ambient light. At 0%, unilluminated areas are black; low levels keep them near black. Ambient light survives saves, exports, Undo/Redo and resizing. Legacy saves retain full ambient light.",
      "Lighting shades particles, elastic/rigid bodies, creatures, missiles and painted backgrounds together in Natural view. Inspect lenses and world thumbnails share it; Temperature, Pressure and Echolocation remain readable. The bounded optical field updates at half the display rate.",
    ],
  },
  {
    version: "1.9.0",
    date: "2026-10-02",
    title: "Predators and heat seekers",
    changes: [
      "Added Wolf and Shark. Cats hunt Rabbits and Birds, Wolves hunt Rabbits and Cats, and Sharks hunt Fish. Prey flee visible predators; bites require contact, respect a cooldown and leave physical ragdolls. Wildlife settings control predation and sensing distance.",
      "Added Heat-Seeking Missile in Devices. Rockets turn gradually toward the nearest exposed hot material, leave smoke trails and explode on swept collisions. Warm, Cool, Fan, Grab and Erase work on them; saves, Undo/Redo and resizing retain them. Missile settings control homing, heat threshold, range, speed and blast radius.",
      "Added Predator reserve and Missile range starting worlds. Inspect shows wildlife behavior and missile target, heat, speed and remaining lifetime.",
      "Player settings now offer left/right joystick placement, size, edge inset and vertical offset. Placement stays clear of the mobile dock, resets held inputs after rotation or changes, and keeps joystick-up jumping and desktop Space/W controls.",
    ],
  },
  {
    version: "1.8.0",
    date: "2026-10-02",
    title: "Creatures and echolocation",
    changes: [
      "Character walking and jump height now scale to body size. Walking covers about one body height per second; jumps preserve horizontal momentum. A* routes use shorter reachable jumps and continue steering in the air.",
      "Added Cat, Rabbit, Fish and Bird to Life, plus a Wildlife pond starting world. Creatures walk, hop, swim or fly with distinct jointed bodies. Fish need cool Water or Brine; birds fall when injured or dead. Bodies burn, break, collide, respond to tools and survive saves and resizing.",
      "Removed Light and Sound materials. Their historical save IDs safely become empty space; Laser, Mirror and Solar Cell remain available.",
      "Added audible, stereo effects for falling powders, heavy body impacts, fizzing chemistry, melting, boiling, splashes, fire, explosions, lightning and birds. Heavier impacts are louder and lower pitched. The listener follows the screen center, or the player while controlling one. Audio unlocks on interaction; Audio settings provide mute and volume.",
      "Added Echolocation beside Natural, Temperature and Pressure. A separate damped sound-wave field reflects from solid barriers, wraps across looping edges, escapes through void edges and loses energy in sponge. Sound waves remain visible with audio muted.",
    ],
  },
  {
    version: "1.7.1",
    date: "2026-10-02",
    title: "Joystick jumping",
    changes: [
      "Removed the separate mobile Jump button. Push the joystick up to jump, or diagonally up to jump while moving. Down crouches; desktop W and Space still jump.",
    ],
  },
  {
    version: "1.7.0",
    date: "2026-10-02",
    title: "Stickmen and player controls",
    changes: [
      "Added Stickman and Player in Life. Characters have jointed bodies, gravity, swept terrain collisions, liquid drag, finite burning fuel, impact damage, breakable limbs, and persistent ragdoll physics. Grab, Fan, Warm, Cool and Erase interact with them.",
      "AI stickmen use bounded A* over supported terrain, with clearance checks, jump and drop edges, and hazard avoidance. They follow a player or patrol terrain; navigation replans as the world changes.",
      "Player controls use A/D to move, W or Space to jump, and S to crouch. Phones and tablets get an on-screen joystick and Jump button. Release controls returns Space to normal sandbox shortcuts; P pauses while playing.",
      "Added Stickman playground. Characters survive saves, autosaves, export/import, Undo/Redo, and canvas resizing. Inspect shows health, joints, heat and navigation state.",
    ],
  },
  {
    version: "1.6.6",
    date: "2026-10-02",
    title: "Shape solids before they fall",
    changes: [
      "Draw automatically pauses physics while drawing moving solids, so a whole shape forms before falling. Mouse, pen, touch, and line/circle/rectangle gestures share this behavior.",
      "Settings → Brush → After drawing solids offers Resume on release or Stay paused. Existing pauses are preserved; canceled strokes and two-finger navigation release the temporary stop safely.",
      "Stationary solid strokes avoid repeated brush work while frozen. Movement and live size/shape changes still update immediately.",
    ],
  },
  {
    version: "1.6.5",
    date: "2026-10-02",
    title: "Pixel material icons",
    changes: [
      "Every material group has its own colored pixel icon: powder grains, liquid droplets, gas puffs, moving solids, static bricks, elastic springs, life leaves, explosive bursts, energy bolts, device gears, and fiction stars.",
      "The material grid and current material details share the same icons, with centered labels on desktop and mobile.",
    ],
  },
  {
    version: "1.6.4",
    date: "2026-10-02",
    title: "Centered material cards",
    changes: [
      "Material icons and labels are centered within each grid card on desktop, phones and tablets, including wrapped names.",
    ],
  },
  {
    version: "1.6.3",
    date: "2026-10-02",
    title: "Material cleanup",
    changes: [
      "Removed both Fit canvas buttons. Mouse, touch, zoom and pan controls remain available.",
      "Removed Plasma, Dragonfire, Frostfire, Fairy Dust, Furnace, Neutron, Nutrient Water, Mica, Sulfur Dioxide and Carbon Dioxide Foam from the palette and active reactions.",
      "Carbon Dioxide is now CO2; Glass Dust is now Glass Shards. Every word in material names starts with a capital letter.",
      "Old save IDs migrate to remaining materials. Fertilizer dissolves into ordinary Water; Acid and Baking Soda produce Water, CO2 and local pressure. Preset fixtures use remaining materials.",
    ],
  },
  {
    version: "1.6.2",
    date: "2026-10-02",
    title: "Rolling solids and faster physics",
    changes: [
      "Solid bodies use friction, material-specific bounce, and angular momentum. Round shapes roll down slopes; ice slides more easily than wood; off-center forces and impacts create spin.",
      "Rotating bodies resolve grid reservations without catching on themselves. Contact faces and other bodies are handled separately, with bounded support forces and weight transfer through stacks.",
      "Chemistry skips inactive rules at stable temperatures while preserving heat, electricity, reactions and phase changes. Pressure gradients are reused until pressure changes; particle swaps and body force/update passes avoid unnecessary work.",
      "Electricity and heat follow structural links through rotating solids. The Live wire fixture has a supported fuse and an insulated spark gap. Rolling, friction, torque, stacks, gravity directions, looping seams and rotating save/load have dedicated regression checks.",
    ],
  },
  {
    version: "1.6.1",
    date: "2026-10-02",
    title: "Two-finger navigation",
    changes: [
      "Two fingers pan the canvas and pinch to zoom around their midpoint on phones and tablets, including rotated views.",
      "A short first-touch grace period prevents accidental dots when starting a gesture. Single-finger taps, strokes, painting, selection, inspection, and bucket fill still work.",
      "Navigation cancels active drawing or selection movement without adding edits. Lifting one finger does not resume drawing; lift both before starting a new stroke.",
      "Touch cancellation and focus changes stop held strokes. Canvas gestures keep the browser page from scrolling or zooming; navigation does not change particles or Undo/Redo history.",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-10-02",
    title: "Bucket fill and moving solid bodies",
    changes: [
      "Added Fill (K) with Material, Foreground color, and Background color targets. The bucket fills connected areas with a single click or tap; material replacement is explicit, and right-click erases a region. Each fill supports Undo/Redo.",
      "Added Static materials with Wall: fixed, indestructible to reactions and impacts, and still editable with drawing, erasing, and selection tools. Preset frames use Wall where they need permanent support.",
      "Solids now fall as connected rigid shapes with mass, rotation, buoyancy, pressure forces, and collision momentum. Heavy impacts damage brittle surfaces; glass shatters, mineral solids form rubble, and wood can splinter into chips. Resting contact does not cause damage.",
      "Rigid shapes keep their geometry when moved with Grab, cut into separate pieces, copied, resized, saved, or restored. They render as continuous bodies and Inspect reports mass, speed, and impact damage.",
      "Simplified elastic connectivity: component membership is rebuilt only after links change, while gravity and spring integration continue every tick. Inspection queries nearby links instead of scanning the entire elastic world.",
      "Consolidated hydrochloric acid, vinegar, and sulfurous acid into one Acid material. Old save IDs and absorbed liquids migrate automatically; foaming, hydrogen production, neutralization, and corrosion use the shared Acid rules.",
      "Fixed diagonal body movement through wall corners, balanced support contacts, and updated containers and circuit fixtures for movable solids. Surface flames retain contact long enough to ignite cold fuel reliably.",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-10-02",
    title: "Fitted canvases, rotating gravity, and foaming chemistry",
    changes: [
      "Removed Draw temperature; placed particles use their substance’s normal starting temperature. Replace now sits beside the material picker on the main drawing controls, with a compact toggle on phones.",
      "Baking soda and vinegar or other acids create CO₂ and an energetic, finite burst of expanding foam. Foam rises, produces local pressure, and collapses back into liquid and gas.",
      "Added local air temperature and barrier-aware atmospheric pressure/heat diffusion. Heating, cooling, boiling, condensation, combustion, and gas-producing/absorbing reactions affect the atmosphere; Inspect and Temperature view reveal it. Atmospheric heat survives saves and resizes.",
      "Replaced generic Gas, Metal, Metal dust, Fuel, Acid, and Insulator with Methane, Steel, Steel powder, Kerosene, Hydrochloric acid, and Mica while preserving existing save IDs. Acid-metal reactions release hydrogen; acids leave glass, oils, and water intact. Sulfur dioxide dissolves into sulfurous acid, and glass melts into molten glass.",
      "Fixed elastic objects catching on their own connected particles. Internal contact retains displacement and momentum instead of rigid bounce and friction; detached pieces still collide, and swept movement cannot skip walls.",
      "The world fills the available drawing area without blank margins. New canvas dimensions come from the screen; removed X/Y size fields and desktop resize handles. Mobile properties offer one pixel resolution for the shorter side.",
      "Rotating a phone keeps the world's particle grid, paint, links, and scene orientation fixed to the device. The view counters browser rotation and gravity follows the bottom of the screen.",
      "Powders, liquids, gases, elastics, surface fire, smoke, lightning, rain, plants, and sponge drainage respect gravity in all four orientations.",
      "Mobile controls always open from the bottom. Drawing, Paint, selection, inspection, zoom, pan, and directional tools use the same rotated view transform.",
      "Changing mobile resolution keeps the crop/expansion placement preview and Undo/Redo. Old saved worlds remain compatible and fill the display without automatic cropping.",
    ],
  },
  {
    version: "1.4.1",
    date: "2026-10-01",
    title: "Paint, elastic motion, and canvas handles",
    changes: [
      "Added Paint with foreground and background layers. Foreground recolors occupied particles and travels with them; background strokes stay at their canvas coordinates. Paint never creates particles or changes their physics.",
      "A circular color swatch opens a touch-friendly wheel, RGB/hex inputs, hue, saturation, brightness, opacity, and a palette. Opacity applies consistently once per stroke. Paint removal restores the original appearance without deleting materials.",
      "Both paint layers survive local saves, export/import, Undo/Redo, and cropping or expanding the canvas. Copying particles includes their foreground coating. Paint has a rebindable O shortcut.",
      "Elastics accelerate and fall faster. Internal damping controls deformation rather than slowing whole-body motion, and smaller physics steps stabilize spring tension.",
      "Fixed thick bodies stalling when their own cells blocked movement. Leading edges move first, and elastic physics continues every simulation tick, including after cuts.",
      "Elastics have a separate smooth rendering pass with connected skins, flexible joints, and thinning under tension. Temperature and pressure views, inspection, previews, and save thumbnails include the same elastic bodies.",
      "Erasing cuts visible stretched links even through empty grid cells. Cut membranes disappear immediately, the resulting pieces stay separate, and tensioned strands can recoil.",
      "Moved Fertilizer from Life into Powders.",
      "Desktop canvases have draggable edge and corner handles. Drag to crop or add space, hold Shift on a corner to preserve aspect ratio, or Escape to cancel. Resizes remain undoable.",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-10-01",
    title: "Elastics and bubbles",
    changes: [
      "Rope, rubber, and jelly keep permanent spring connections from their drawn shape. They bend, stretch, react to gravity and pressure, and can be moved with Grab. Drawing against a solid anchors the attached end; erasing its support releases it.",
      "Added soap, soapy water, and bubbles. Soap dissolves into water, agitation or warming makes bubbles, and bubbles rise through liquids and pop under heat, pressure, or with age.",
      "Each substance has one palette entry. Alternate phases still exist in the simulation; Draw temperature lets you create hot, molten, gaseous, or frozen forms. Copy picks the substance and its sampled temperature.",
      "Reorganized the palette by behavior, including Elastics, Life, Explosives, Devices, and Fiction. Ordinary solids remain rigid.",
      "Mobile controls now group Playback and Edit at the top, followed by Tool & brush, material or tool properties, and View. Mobile material tiles have equal widths and heights.",
      "Elastic links survive save/load, undo/redo, moving selections, and canvas resizing; copied selections receive independent links. Older saves remain compatible.",
    ],
  },
  {
    version: "1.3.1",
    date: "2026-10-01",
    title: "Phone rotation and fullscreen",
    changes: [
      "Replaced the Controls caption with a grip and reduced the collapsed mobile dock to one row.",
      "Fullscreen now has an always-visible exit button on mobile.",
      "Rotating a phone into landscape refits the canvas and enters canvas focus. Tall canvases align left; the panel uses the side or bottom according to which fits the canvas best.",
      "Side panels expand with a horizontal swipe, bottom panels with an upward swipe. Rotation preserves particles and returns to the portrait layout when turned upright.",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-10-01",
    title: "Drawing and canvas space",
    changes: [
      "Shift-drag previews a straight line. Control-drag previews a circle or rectangle outline using the current brush shape; release to draw, or Escape to cancel.",
      "Scroll adjusts brush size. Control-scroll zooms around the pointer; middle-drag pans and Fit resets the view.",
      "Phones now prioritize the canvas with a compact bottom dock. Swipe up or tap Controls for brush, history, tool properties, and zoom controls.",
      "Canvas focus works on iPhone Safari without requiring browser fullscreen. The material browser still opens with its slide animation, including in landscape.",
    ],
  },
  {
    version: "1.2.2",
    date: "2026-10-01",
    title: "Mobile toolbar",
    changes: [
      "Fixed the Natural view switch overlapping Trash on mobile. Undo, Redo, Trash, visualization, and materials now share an aligned row with distinct touch targets.",
    ],
  },
  {
    version: "1.2.1",
    date: "2026-10-01",
    title: "Tool names",
    changes: [
      "Renamed Paint to Draw, Magnifier to Inspect, and Eyedropper to Copy in the tool picker and keyboard settings.",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-10-01",
    title: "Energy and imagination",
    changes: [
      "Every tool now has a matching line icon in a touch-friendly dropdown with keyboard navigation.",
      "Added light, lasers, sound, neutrons, mirrors, solar cells, uranium, and glass dust.",
      "Light reflects from mirrors, passes through glass and water, and powers solar cells. Lasers heat targets; sound makes pressure pulses; neutrons trigger uranium fission.",
      "Added dragonfire, frostfire, antimatter, black holes, repulsors, and fairy dust, with a Fiction filter in the material palette.",
      "Ray direction survives copying, resizing, undo, and save files. Existing saves and material IDs remain compatible.",
      "Lightning brush size controls strike frequency: small brushes strike slowly, large brushes strike rapidly. Clicks and taps remain immediate.",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-10-01",
    title: "Canvas creation and resizing",
    changes: [
      "Replaced Experiments with a plus button for creating named canvases with custom pixel dimensions, borders, and background colors.",
      "Canvas properties can be edited beside the canvas size. Resizing includes a draggable placement preview for cropping or adding space.",
      "Solid borders contain particles, looping borders connect opposite edges, and void borders let particles escape. Reactions, heat, and pressure follow the border type.",
      "Canvas properties and complete particle state survive saves, exports, autosave, undo, and redo.",
      "Fixed a timing issue that could override pause shortcuts pressed immediately after closing a menu.",
    ],
  },
  {
    version: "1.0.1",
    date: "2026-10-01",
    title: "About Sandlab",
    changes: [
      "The question mark menu now shows the app version, changelog, and local storage information.",
      "Removed the redundant controls list. Keyboard bindings remain in Settings → Keyboard.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Inspection and keyboard controls",
    changes: [
      "Added a magnifier with live temperature, lifetime, charge, pressure, and material-specific readings.",
      "Added an eyedropper to pick a material directly from the world.",
      "Keyboard shortcuts can be changed, cleared, or reset in Settings → Keyboard. Help displays your current bindings.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Edit history and reaction timing",
    changes: [
      "Added redo, cut, select all, delete selection, and common desktop shortcuts.",
      "Added this changelog under Help → What’s new.",
      "Gunpowder burns progressively and builds pressure; liquid fuel burns at exposed surfaces.",
      "TNT heats up before a delayed reaction; strong pressure can still trigger it rapidly.",
      "Burning coal, wood, and gunpowder emit hot embers. Conductors spark across small electrical gaps.",
      "Cold water quenches without instant vaporization; brine retains salt through boiling and freezing.",
      "Removed Terrarium. New sessions start with an empty world.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Public access and security",
    changes: [
      "Made Sandlab playable without a ChatGPT sign-in.",
      "Blocked remote scripts and network connections, removed remote fonts, and hardened save imports.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Materials and experiments",
    changes: [
      "Expanded the palette to 71 materials, including copper, sodium, clay, fertilizer, and liquid nitrogen.",
      "Added oxidation, neutralization, nutrient transport, and ceramic firing.",
      "Added Reaction bench and Pottery kiln.",
    ],
  },
  {
    date: "Earlier updates",
    title: "Sandbox controls",
    changes: [
      "Added lightning, growing plants, bloom, absorption, temperature tools, and force tools.",
      "Added rectangle and brush selections, copying, pasting, dragging, and deselection.",
      "Added grouped settings and a full-height mobile materials palette.",
    ],
  },
];
