export const changelog = [
  {
    version: "1.5.0",
    date: "2026-10-02",
    title: "Fitted canvases, rotating gravity, and foaming chemistry",
    changes: [
      "Removed Draw temperature; placed particles use their substance’s normal starting temperature. Replace now sits beside the material picker on the main drawing controls, with a compact toggle on phones.",
      "Baking soda and vinegar or other acids create CO₂ and an energetic, finite burst of expanding foam. Foam rises, produces local pressure, and collapses back into liquid and gas.",
      "Added local air temperature and barrier-aware atmospheric pressure/heat diffusion. Heating, cooling, boiling, condensation, combustion, and gas-producing/absorbing reactions affect the atmosphere; Inspect and Temperature view reveal it. Atmospheric heat survives saves and resizes.",
      "Replaced generic Gas, Metal, Metal dust, Fuel, Acid, and Insulator with Methane, Steel, Steel powder, Kerosene, Hydrochloric acid, and Mica while preserving existing save IDs. Acid-metal reactions release hydrogen; acids leave glass, oils, and water intact. Sulfur dioxide dissolves into sulfurous acid, and glass melts into molten glass.",
      "Fixed elastic objects catching on their own connected particles. Internal contact retains displacement and momentum instead of rigid bounce and friction; detached pieces still collide, and swept movement cannot skip walls.",
      "The world fills the available drawing area without blank margins. New canvas dimensions come from the screen; removed X/Y size fields and desktop resize handles. Mobile properties offer one pixel resolution for the shorter side.",
      "Rotating a phone keeps the world's particle grid, paint, links, and scene orientation fixed to the device. The view counters browser rotation and gravity follows the bottom of the screen.",
      "Powders, liquids, gases, elastics, surface fire, smoke, lightning, rain, plants, and sponge drainage respect gravity in all four orientations.",
      "Mobile controls always open from the bottom. Drawing, Paint, selection, inspection, zoom, pan, and directional tools use the same rotated view transform.",
      "Changing mobile resolution keeps the crop/expansion placement preview and Undo/Redo. Old saved worlds remain compatible and fill the display without automatic cropping.",
    ],
  },
  {
    version: "1.4.1",
    date: "2026-10-01",
    title: "Paint, elastic motion, and canvas handles",
    changes: [
      "Added Paint with foreground and background layers. Foreground recolors occupied particles and travels with them; background strokes stay at their canvas coordinates. Paint never creates particles or changes their physics.",
      "A circular color swatch opens a touch-friendly wheel, RGB/hex inputs, hue, saturation, brightness, opacity, and a palette. Opacity applies consistently once per stroke. Paint removal restores the original appearance without deleting materials.",
      "Both paint layers survive local saves, export/import, Undo/Redo, and cropping or expanding the canvas. Copying particles includes their foreground coating. Paint has a rebindable O shortcut.",
      "Elastics accelerate and fall faster. Internal damping controls deformation rather than slowing whole-body motion, and smaller physics steps stabilize spring tension.",
      "Fixed thick bodies stalling when their own cells blocked movement. Leading edges move first, and elastic physics continues every simulation tick, including after cuts.",
      "Elastics have a separate smooth rendering pass with connected skins, flexible joints, and thinning under tension. Temperature and pressure views, inspection, previews, and save thumbnails include the same elastic bodies.",
      "Erasing cuts visible stretched links even through empty grid cells. Cut membranes disappear immediately, the resulting pieces stay separate, and tensioned strands can recoil.",
      "Moved Fertilizer from Life into Powders.",
      "Desktop canvases have draggable edge and corner handles. Drag to crop or add space, hold Shift on a corner to preserve aspect ratio, or Escape to cancel. Resizes remain undoable.",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-10-01",
    title: "Elastics and bubbles",
    changes: [
      "Rope, rubber, and jelly keep permanent spring connections from their drawn shape. They bend, stretch, react to gravity and pressure, and can be moved with Grab. Drawing against a solid anchors the attached end; erasing its support releases it.",
      "Added soap, soapy water, and bubbles. Soap dissolves into water, agitation or warming makes bubbles, and bubbles rise through liquids and pop under heat, pressure, or with age.",
      "Each substance has one palette entry. Alternate phases still exist in the simulation; Draw temperature lets you create hot, molten, gaseous, or frozen forms. Copy picks the substance and its sampled temperature.",
      "Reorganized the palette by behavior, including Elastics, Life, Explosives, Devices, and Fiction. Ordinary solids remain rigid.",
      "Mobile controls now group Playback and Edit at the top, followed by Tool & brush, material or tool properties, and View. Mobile material tiles have equal widths and heights.",
      "Elastic links survive save/load, undo/redo, moving selections, and canvas resizing; copied selections receive independent links. Older saves remain compatible.",
    ],
  },
  {
    version: "1.3.1",
    date: "2026-10-01",
    title: "Phone rotation and fullscreen",
    changes: [
      "Replaced the Controls caption with a grip and reduced the collapsed mobile dock to one row.",
      "Fullscreen now has an always-visible exit button on mobile.",
      "Rotating a phone into landscape refits the canvas and enters canvas focus. Tall canvases align left; the panel uses the side or bottom according to which fits the canvas best.",
      "Side panels expand with a horizontal swipe, bottom panels with an upward swipe. Rotation preserves particles and returns to the portrait layout when turned upright.",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-10-01",
    title: "Drawing and canvas space",
    changes: [
      "Shift-drag previews a straight line. Control-drag previews a circle or rectangle outline using the current brush shape; release to draw, or Escape to cancel.",
      "Scroll adjusts brush size. Control-scroll zooms around the pointer; middle-drag pans and Fit resets the view.",
      "Phones now prioritize the canvas with a compact bottom dock. Swipe up or tap Controls for brush, history, tool properties, and zoom controls.",
      "Canvas focus works on iPhone Safari without requiring browser fullscreen. The material browser still opens with its slide animation, including in landscape.",
    ],
  },
  {
    version: "1.2.2",
    date: "2026-10-01",
    title: "Mobile toolbar",
    changes: [
      "Fixed the Natural view switch overlapping Trash on mobile. Undo, Redo, Trash, visualization, and materials now share an aligned row with distinct touch targets.",
    ],
  },
  {
    version: "1.2.1",
    date: "2026-10-01",
    title: "Tool names",
    changes: [
      "Renamed Paint to Draw, Magnifier to Inspect, and Eyedropper to Copy in the tool picker and keyboard settings.",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-10-01",
    title: "Energy and imagination",
    changes: [
      "Every tool now has a matching line icon in a touch-friendly dropdown with keyboard navigation.",
      "Added light, lasers, sound, neutrons, mirrors, solar cells, uranium, and glass dust.",
      "Light reflects from mirrors, passes through glass and water, and powers solar cells. Lasers heat targets; sound makes pressure pulses; neutrons trigger uranium fission.",
      "Added dragonfire, frostfire, antimatter, black holes, repulsors, and fairy dust, with a Fiction filter in the material palette.",
      "Ray direction survives copying, resizing, undo, and save files. Existing saves and material IDs remain compatible.",
      "Lightning brush size controls strike frequency: small brushes strike slowly, large brushes strike rapidly. Clicks and taps remain immediate.",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-10-01",
    title: "Canvas creation and resizing",
    changes: [
      "Replaced Experiments with a plus button for creating named canvases with custom pixel dimensions, borders, and background colors.",
      "Canvas properties can be edited beside the canvas size. Resizing includes a draggable placement preview for cropping or adding space.",
      "Solid borders contain particles, looping borders connect opposite edges, and void borders let particles escape. Reactions, heat, and pressure follow the border type.",
      "Canvas properties and complete particle state survive saves, exports, autosave, undo, and redo.",
      "Fixed a timing issue that could override pause shortcuts pressed immediately after closing a menu.",
    ],
  },
  {
    version: "1.0.1",
    date: "2026-10-01",
    title: "About Sandlab",
    changes: [
      "The question mark menu now shows the app version, changelog, and local storage information.",
      "Removed the redundant controls list. Keyboard bindings remain in Settings → Keyboard.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Inspection and keyboard controls",
    changes: [
      "Added a magnifier with live temperature, lifetime, charge, pressure, and material-specific readings.",
      "Added an eyedropper to pick a material directly from the world.",
      "Keyboard shortcuts can be changed, cleared, or reset in Settings → Keyboard. Help displays your current bindings.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Edit history and reaction timing",
    changes: [
      "Added redo, cut, select all, delete selection, and common desktop shortcuts.",
      "Added this changelog under Help → What’s new.",
      "Gunpowder burns progressively and builds pressure; liquid fuel burns at exposed surfaces.",
      "TNT heats up before a delayed reaction; strong pressure can still trigger it rapidly.",
      "Burning coal, wood, and gunpowder emit hot embers. Conductors spark across small electrical gaps.",
      "Cold water quenches without instant vaporization; brine retains salt through boiling and freezing.",
      "Removed Terrarium. New sessions start with an empty world.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Public access and security",
    changes: [
      "Made Sandlab playable without a ChatGPT sign-in.",
      "Blocked remote scripts and network connections, removed remote fonts, and hardened save imports.",
    ],
  },
  {
    date: "2026-10-01",
    title: "Materials and experiments",
    changes: [
      "Expanded the palette to 71 materials, including copper, sodium, clay, fertilizer, and liquid nitrogen.",
      "Added oxidation, neutralization, nutrient transport, and ceramic firing.",
      "Added Reaction bench and Pottery kiln.",
    ],
  },
  {
    date: "Earlier updates",
    title: "Sandbox controls",
    changes: [
      "Added lightning, growing plants, bloom, absorption, temperature tools, and force tools.",
      "Added rectangle and brush selections, copying, pasting, dragging, and deselection.",
      "Added grouped settings and a full-height mobile materials palette.",
    ],
  },
];
